### ISSUE TITLE
problems with the weakness effect

### ISSUE THREAD

**Issue by moderator10000078** [VidTu/HCsCR#3]
the crystal disappears on the client if the player cannot break it due to the effect of weakness, it simply disappears, but does not explode, such a phantom crystal does not take damage with a sword, but can be blown up with a shot from a crossbow

when removing a crystal, it is worth checking whether the player can blow it up

**Comment by Offenderify** [comment]
Will be fixed later, we need to release now.

**Comment by VidTu** [comment]
Hruk 🐽
